### ISSUE TITLE
Animation layer for object animations

### ISSUE THREAD

**Issue by adamreisnz** [adamreisnz/ngGo#10]
Create a new animation layer and let it have an interval of redrawing 30 times per second, whenever there is an animation object in place. Add callbacks for when the animation is finished (for example, add stone to the actual static stones layer).

**Comment by AdamBuczynski** [comment]
Moving to 1.2.0, as animations are probably easier to accomplish using SVG board rendering.

**Comment by adamreisnz** [comment]
Not implementing for now
